# Generated by Django 4.2.10 on 2025-04-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_teams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=100)),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losing_mini_games', to='app_teams.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_games', to='app_teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_mini_games', to='app_teams.team')),
            ],
            options={
                'verbose_name': 'Mini Game',
                'verbose_name_plural': 'Mini Games',
            },
        ),
    ]
