# Generated by Django 5.1.1 on 2025-02-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_games', '0001_initial'),
        ('app_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigame',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losing_mini_games', to='app_teams.team'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_games', to='app_teams.team'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_mini_games', to='app_teams.team'),
        ),
    ]
