# Generated by Django 4.2.10 on 2025-04-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-is_read', '-timestamp'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
    ]
