# Generated by Django 4.2.10 on 2025-04-16 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('example', models.TextField()),
                ('status', models.CharField(choices=[('to_learn', 'To Learn'), ('known', 'Known'), ('learned', 'Learned')], default='to_learn', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_cards', to='app_teams.team')),
            ],
            options={
                'verbose_name': 'Word Card',
                'verbose_name_plural': 'Word Cards',
            },
        ),
        migrations.CreateModel(
            name='PrivateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('to_learn', 'To Learn'), ('known', 'Known'), ('learned', 'Learned')], default='to_learn', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Card',
                'verbose_name_plural': 'Private Cards',
            },
        ),
    ]
