# Generated by Django 5.1.1 on 2025-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher')], default='user', max_length=50),
        ),
    ]
